[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -Xmx512m -jar /app/app.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Alternative: if Dockerfile fails, use this instead:
# [build]
# builder = "NIXPACKS"
#
# [deploy]
# startCommand = "bash run-demo.sh"
