name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: bash scripts/fix_near_types.sh
      - run: ./gradlew :near-jsonrpc-client:generateKotlinClient
      - run: ./gradlew build
      - run: ./gradlew :near-jsonrpc-client:test :near-jsonrpc-client:jacocoTestReport
