name: Deploy Demo

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3

      - name: Build demo JAR
        run: |
          bash scripts/fix_near_types.sh
          ./gradlew :demo-app:shadowJar

      - name: Build Docker image
        run: docker build -t near-kotlin-demo .

      # Add your deployment steps here for Railway, Render, etc.
      # Example for Docker Hub:
      # - name: Push to Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker tag near-kotlin-demo ${{ secrets.DOCKER_USERNAME }}/near-kotlin-demo:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/near-kotlin-demo:latest
